### PR TITLE
Ak hi

### PR DESCRIPTION
**Pull request by TheMiloAnderson**
Moved and scaled Alaska & Hawaii geojson; put polygon boxes around them

### CODE REVIEW

**Comment by TheMiloAnderson** [comment]
Do you mean like entirely separate 'map' objects/html elements, and then use CSS positioning to overlay them? Or does Leaflet have a way to do this in the same object with layers or something?

Partly I was thinking to keep things on the same map in case we wanted to allow zooming and panning. Is there a reason those are disabled? Seems like it would be very useful for people to see some of the really tiny districts. 

If we wanted to locate events we could do it by running lat & long through the same arithmetic I used to alter the maps: AK: long = long * .2 - 99, lat = lat * .34 + 15.5; HI: long = long * 1.4 + 91; lat = lat * 1.2 + 5. I could write a function to do the geojson changes on the fly, to make things more explicit. 

Happy to do it any other way if you have a strong preference, tho.

**Comment by meganrm** [comment]
As we discussed: 1. state geojson needs the same adjustment. 2 . bboxes file needs to have 'AK' and 'HI' changed so that clicking on these states would move to the inset. 3. states-centers needs to be adjusted so senators show up in states view

**Comment by meganrm** [comment]
something weird is happening with the HI senators when you click between the tabs

**Comment by TheMiloAnderson** [comment]
I see what you mean, looking into it...

**Comment by TheMiloAnderson** [comment]
It was actually happening with all the states, but Hawaii is the only one that doesn't have opaque landmass covering up the Senator markers in the districts map. 

Should be fixed now.

**Pull request merged**
